### ISSUE TITLE
Add facebook icon/link to menu

### ISSUE THREAD

**Issue by savvysoftworks** [ninjapanzer/savvyshots#24]

**Comment by ninjapanzer** [comment]
Can I have URLs to your pages

**Comment by savvysoftworks** [comment]
Facebook.com/savvyshotsphotography

**Comment by ninjapanzer** [comment]
![f_icon_savvy](https://cloud.githubusercontent.com/assets/159591/6638564/b59cb504-c95d-11e4-8456-ca70c9a98906.png)

What do you think?

**Comment by ninjapanzer** [comment]
![screen shot 2015-03-13 at 9 43 07 am](https://cloud.githubusercontent.com/assets/159591/6639387/826f7146-c965-11e4-807a-601a4213aa89.png)

Deployed

**Comment by savvysoftworks** [comment]
Oh! I love it!
